# Generated by Django 5.1 on 2026-01-30 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stickysender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_senders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stickysender',
            index=models.Index(fields=['user'], name='sms_sticky__user_id_e4e769_idx'),
        ),
        migrations.AddIndex(
            model_name='stickysender',
            index=models.Index(fields=['updated_at'], name='sms_sticky__updated_fd59fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stickysender',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_sticky_sender'),
        ),
    ]
