# Generated by Django 5.1 on 2026-01-31 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StickySender',
        ),
    ]
